### ISSUE TITLE
[Suggestion] App Drawer Complication

### ISSUE THREAD

**Issue by eliasacab** [amoledwatchfaces/Complications-Suite-Wear-OS#20]
A complication that when pressed opens the native app drawer. Useful for watches like the Pixel Watch which require the crown to be pressed to open the app drawer, unlike Samsung watches.

Thanks!

**Comment by amoledwatchfaces** [comment]
Hi. I don't think something like this will be possible. App drawer can be opened only by Android launcher afaik.
Maybe you can try using Favorite Apps Tile? It was created mainly for Pixel Watches because of the app drawer accessibility issue. 

https://play.google.com/store/apps/details?id=com.weartools.favoriteappstile

**Comment by eliasacab** [comment]
Thanks for the suggestion!
